name: "Release"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  release:
    types:
      - "published"

permissions: {}

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build
        run: |
          set -x  # Enable debug output
          nix-build default.nix
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aws-signing-helper
          path: result
        if: success()

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        if: github.event_name == 'release' && github.event.action == 'published'
        with:
          files: |
            result/*
          fail_on_unmatched_files: true
          generate_release_notes: true
