name: "Release"

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
  release:
    types:
      - "published"

permissions: {}

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build
        run: |
          set -x  # Enable debug output
          nix-build default.nix
        
      - name: Upload to GitHub Releases
        uses: actions/upload-artifact@v4
        with:
          name: aws-signing-helper
          path: result
        if: success()
